# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e329aaa6cffcc12d0a14723f96a280ed02890a8fe2f3d86fa1283ad6aff41ee8697d9a1698c406f7235bacf2495d54c55ea3665efe34e7b230d23a84c11a805

test:
  secret_key_base: f0988170b82615d7631e103838a6e13cf28eddb3d4a39adb5790e584501f535c3ba6618fc34cf47747fd22e70941e7eed9ca2f0d2ed2d9ff5c75cdcfad07bf34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
